### ISSUE TITLE
why no ssh-copy-id

### ISSUE THREAD

**Issue by Pzdrs** [Bahamut731lp/PBE#1]
docker very good yes i like

10/10 would steal again

**Comment by Bahamut731lp** [comment]
> why no ssh-copy-id

Protože `root` na ubuntu v dockeru nemá heslo, a abych mohl `ssh-copy-id`, musim přitom zadat heslo roota. Ho akorát změň ne? Nj, ale i tak to nešlo :)

Jsem se s tim nechtěl patlat a prostě to překopíroval lol.

PS.: To další cvičení je taky v dockeru a je to zatím hodně wicked

**Comment by Pzdrs** [comment]
udelal jsem copy-id no s heslem a PermitRootLogin.

PS: looking forward to it my friend, mnohem lepsi nez chodit do ty smradlavy ucebny nefunkcni
